spring:
  application:
    name: order-service
    
#server:
#  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
rabbitmq:
  host: 192.168.232.133
  port: 5672
  username: admin
  password: admin      
---
spring:
  profiles: order1
  
server:
  port: 8201
---
spring:
  profiles: order2

server:
  port: 8202
  
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        

      